main: net.hashcodedevelopement.chataddon.ChatAddon

name: HashCodeDev-ChatAddon
author: Cerus
version: 1.0
description: ChatAddon developed by HashCodeDevelopment. You are not allowed to sell, share or decompile this plugin without our permission.